### ISSUE TITLE
Testing exact compressed data lengths is too brittle

### ISSUE THREAD

**Issue by musicinmybrain** [cramjam/libcramjam#6]
Since compression libraries do not in general attempt to preserve the exact same compressed output for each compressed input across compatible releases, testing exact compressed data lengths is brittle – too brittle, in my opinion.

This is visible in current `main`, 1d959cfd8abadaa1fb1bbf05d9c37b0596ac6e48 since the release of [`lz4`](https://crates.io/crates/lz4) 1.25.

```
---- tests::lz4::roundtrip_compress_via_slice_decompress_via_vector stdout ----
thread 'tests::lz4::roundtrip_compress_via_slice_decompress_via_vector' panicked at src/lib.rs:106:5:
assertion `left == right` failed
  left: 329646
 right: 303278
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::lz4::roundtrip_compress_via_slice_decompress_via_slice stdout ----
thread 'tests::lz4::roundtrip_compress_via_slice_decompress_via_slice' panicked at src/lib.rs:106:5:
assertion `left == right` failed
  left: 329646
 right: 303278

---- tests::lz4::roundtrip_compress_via_vector_decompress_via_slice stdout ----
thread 'tests::lz4::roundtrip_compress_via_vector_decompress_via_slice' panicked at src/lib.rs:106:5:
assertion `left == right` failed
  left: 329646
 right: 303278

---- tests::lz4::roundtrip_compress_via_vector_decompress_via_vector stdout ----
thread 'tests::lz4::roundtrip_compress_via_vector_decompress_via_vector' panicked at src/lib.rs:106:5:
assertion `left == right` failed
  left: 329646
 right: 303278


failures:
    tests::lz4::roundtrip_compress_via_slice_decompress_via_slice
    tests::lz4::roundtrip_compress_via_slice_decompress_via_vector
    tests::lz4::roundtrip_compress_via_vector_decompress_via_slice
    tests::lz4::roundtrip_compress_via_vector_decompress_via_vector
```

In this case,

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 8581669..2460462 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -103,7 +103,7 @@ mod tests {
     test_variant!(zstd, compressed_len = 4990, None);
 
     #[cfg(feature = "lz4")]
-    test_variant!(lz4, compressed_len = 303_278, None);
+    test_variant!(lz4, compressed_len = 329_646, None);
 
     #[cfg(feature = "blosc2")]
     test_variant!(blosc2, compressed_len = 791_923);
```

would fix the regression, but perhaps it would be better to omit

https://github.com/cramjam/libcramjam/blob/1d959cfd8abadaa1fb1bbf05d9c37b0596ac6e48/src/lib.rs#L52

altogether.

**Comment by milesgranger** [comment]
Closed with https://github.com/cramjam/libcramjam/pull/8/commits/81afd2eea10f693bafcb59295814aac6b64a4b73 in #8
